
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.9.1
 * Query Engine version: e922089b7d7502aff4249d5da3420f6fa55fc6ad
 */
Prisma.prismaVersion = {
  client: "7.9.1",
  engine: "e922089b7d7502aff4249d5da3420f6fa55fc6ad"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadCommitted: 'ReadCommitted',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  bio: 'bio',
  phone: 'phone',
  username: 'username',
  usn: 'usn',
  lightTheme: 'lightTheme',
  darkTheme: 'darkTheme',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  displayName: 'displayName',
  college: 'college',
  role: 'role',
  year: 'year',
  branch: 'branch',
  isAiml: 'isAiml',
  isLateral: 'isLateral',
  onboardingComplete: 'onboardingComplete',
  hackerrankUsername: 'hackerrankUsername',
  leetcodeProfile: 'leetcodeProfile',
  githubProfile: 'githubProfile',
  skills: 'skills',
  languages: 'languages',
  careerIntent: 'careerIntent',
  marathonStreak: 'marathonStreak',
  marathonTotalScore: 'marathonTotalScore'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.AccountScalarFieldEnum = {
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudentScalarFieldEnum = {
  id: 'id',
  image: 'image',
  userId: 'userId'
};

exports.Prisma.CoreScalarFieldEnum = {
  id: 'id',
  year: 'year',
  userId: 'userId',
  image: 'image',
  order: 'order',
  post: 'post',
  quote: 'quote',
  section: 'section'
};

exports.Prisma.FacultyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  designation: 'designation',
  image: 'image',
  about: 'about',
  order: 'order',
  published: 'published',
  designation2: 'designation2'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  image: 'image',
  date: 'date',
  time: 'time',
  reportLink: 'reportLink',
  venue: 'venue',
  guests: 'guests',
  published: 'published',
  type: 'type',
  status: 'status',
  maxTeamSize: 'maxTeamSize',
  minTeamSize: 'minTeamSize',
  brief: 'brief',
  entryFee: 'entryFee',
  qr: 'qr',
  registrationsAvailable: 'registrationsAvailable',
  endDate: 'endDate',
  maxTeams: 'maxTeams',
  notification: 'notification'
};

exports.Prisma.EventCustomFieldScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  label: 'label',
  fieldType: 'fieldType',
  isRequired: 'isRequired',
  options: 'options',
  order: 'order'
};

exports.Prisma.LinksScalarFieldEnum = {
  id: 'id',
  instagram: 'instagram',
  linkedin: 'linkedin',
  github: 'github',
  userId: 'userId',
  twitter: 'twitter',
  order: 'order',
  custom: 'custom'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  attended: 'attended',
  eventId: 'eventId',
  name: 'name',
  leaderId: 'leaderId',
  transactionId: 'transactionId',
  isConfirmed: 'isConfirmed',
  teamCode: 'teamCode',
  status: 'status',
  customFieldResponses: 'customFieldResponses'
};

exports.Prisma.EventRegistrationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  teamId: 'teamId',
  customFieldResponses: 'customFieldResponses',
  createdAt: 'createdAt'
};

exports.Prisma.FormScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  published: 'published',
  startTime: 'startTime',
  endTime: 'endTime',
  requireAiml: 'requireAiml',
  allowEdit: 'allowEdit',
  createdAt: 'createdAt'
};

exports.Prisma.FormFieldScalarFieldEnum = {
  id: 'id',
  formId: 'formId',
  label: 'label',
  type: 'type',
  options: 'options',
  isRequired: 'isRequired',
  order: 'order'
};

exports.Prisma.FormResponseScalarFieldEnum = {
  id: 'id',
  formId: 'formId',
  userId: 'userId',
  answers: 'answers',
  createdAt: 'createdAt'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  authorId: 'authorId'
};

exports.Prisma.MarathonDailyContestScalarFieldEnum = {
  id: 'id',
  dayNumber: 'dayNumber',
  targetYear: 'targetYear',
  date: 'date',
  title: 'title',
  description: 'description',
  link: 'link',
  slug: 'slug',
  isConfirmed: 'isConfirmed'
};

exports.Prisma.MarathonDailyScoreScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  contestId: 'contestId',
  score: 'score',
  completed: 'completed',
  updatedAt: 'updatedAt'
};

exports.Prisma.MarathonWeeklyContestScalarFieldEnum = {
  id: 'id',
  weekNumber: 'weekNumber',
  targetYear: 'targetYear',
  date: 'date',
  deadline: 'deadline',
  title: 'title',
  description: 'description',
  link: 'link',
  slug: 'slug',
  isConfirmed: 'isConfirmed'
};

exports.Prisma.MarathonWeeklyScoreScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  contestId: 'contestId',
  score: 'score',
  completed: 'completed',
  updatedAt: 'updatedAt'
};

exports.Prisma.WinnersScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  eventId: 'eventId',
  position: 'position'
};

exports.Prisma.PlacementScalarFieldEnum = {
  id: 'id',
  yearId: 'yearId',
  studentId: 'studentId'
};

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  image: 'image'
};

exports.Prisma.OfferScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  package: 'package'
};

exports.Prisma.YearScalarFieldEnum = {
  id: 'id',
  year: 'year',
  companies: 'companies'
};

exports.Prisma.PatentsScalarFieldEnum = {
  id: 'id',
  patentId: 'patentId',
  year: 'year',
  title: 'title',
  authors: 'authors',
  inventorsName: 'inventorsName',
  inventorsAddress: 'inventorsAddress',
  certificate: 'certificate'
};

exports.Prisma.PublicationScalarFieldEnum = {
  id: 'id',
  authors: 'authors',
  title: 'title',
  publish_date: 'publish_date',
  publisher: 'publisher',
  journal: 'journal',
  conference: 'conference',
  link: 'link',
  ranking: 'ranking',
  impact_factor: 'impact_factor',
  indexed: 'indexed',
  publisher_conference: 'publisher_conference',
  year: 'year'
};

exports.Prisma.MarathonClassScalarFieldEnum = {
  id: 'id',
  date: 'date',
  batches: 'batches',
  topic: 'topic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MarathonAttendanceScalarFieldEnum = {
  id: 'id',
  classId: 'classId',
  userId: 'userId',
  batch: 'batch',
  present: 'present',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  OWNER: 'OWNER'
};

exports.CareerIntent = exports.$Enums.CareerIntent = {
  PLACEMENT: 'PLACEMENT',
  HIGHER_STUDIES: 'HIGHER_STUDIES',
  NO: 'NO'
};

exports.TeamSection = exports.$Enums.TeamSection = {
  ADMIN: 'ADMIN',
  TECHNICAL: 'TECHNICAL',
  SPORTS: 'SPORTS',
  CULTURAL: 'CULTURAL',
  GRAPHICS: 'GRAPHICS',
  MEDIA: 'MEDIA',
  EVENT: 'EVENT',
  REPRESENTATIVE: 'REPRESENTATIVE'
};

exports.EventType = exports.$Enums.EventType = {
  SOLO: 'SOLO',
  TEAM: 'TEAM'
};

exports.EventStatus = exports.$Enums.EventStatus = {
  DRAFT: 'DRAFT',
  UPCOMING: 'UPCOMING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED'
};

exports.TeamStatus = exports.$Enums.TeamStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED'
};

exports.WinnerType = exports.$Enums.WinnerType = {
  FIRST: 'FIRST',
  SECOND: 'SECOND',
  THIRD: 'THIRD',
  PARTICIPATION: 'PARTICIPATION'
};

exports.Prisma.ModelName = {
  User: 'User',
  VerificationToken: 'VerificationToken',
  Account: 'Account',
  Session: 'Session',
  Student: 'Student',
  Core: 'Core',
  Faculty: 'Faculty',
  Event: 'Event',
  EventCustomField: 'EventCustomField',
  Links: 'Links',
  Team: 'Team',
  EventRegistration: 'EventRegistration',
  Form: 'Form',
  FormField: 'FormField',
  FormResponse: 'FormResponse',
  Announcement: 'Announcement',
  MarathonDailyContest: 'MarathonDailyContest',
  MarathonDailyScore: 'MarathonDailyScore',
  MarathonWeeklyContest: 'MarathonWeeklyContest',
  MarathonWeeklyScore: 'MarathonWeeklyScore',
  Winners: 'Winners',
  Placement: 'Placement',
  Company: 'Company',
  Offer: 'Offer',
  Year: 'Year',
  Patents: 'Patents',
  Publication: 'Publication',
  MarathonClass: 'MarathonClass',
  MarathonAttendance: 'MarathonAttendance'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
