/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip,
} = require("./runtime/index-browser.js");

const Prisma = {};

exports.Prisma = Prisma;
exports.$Enums = {};

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
Prisma.prismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3",
};

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.Decimal = Decimal;

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.validator = Public.validator;

/**
 * Extensions
 */
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull;
Prisma.JsonNull = JsonNull;
Prisma.AnyNull = AnyNull;

Prisma.NullTypes = NullTypes;

/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadCommitted: "ReadCommitted",
  Serializable: "Serializable",
});

exports.Prisma.UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  emailVerified: "emailVerified",
  image: "image",
  bio: "bio",
  phone: "phone",
  username: "username",
  usn: "usn",
  lightTheme: "lightTheme",
  darkTheme: "darkTheme",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  displayName: "displayName",
  college: "college",
  role: "role",
};

exports.Prisma.AccountScalarFieldEnum = {
  userId: "userId",
  type: "type",
  provider: "provider",
  providerAccountId: "providerAccountId",
  refresh_token: "refresh_token",
  access_token: "access_token",
  expires_at: "expires_at",
  token_type: "token_type",
  scope: "scope",
  id_token: "id_token",
  session_state: "session_state",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
};

exports.Prisma.SessionScalarFieldEnum = {
  sessionToken: "sessionToken",
  userId: "userId",
  expires: "expires",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
};

exports.Prisma.StudentScalarFieldEnum = {
  id: "id",
  image: "image",
  userId: "userId",
};

exports.Prisma.CoreScalarFieldEnum = {
  id: "id",
  year: "year",
  userId: "userId",
  image: "image",
  order: "order",
  post: "post",
  quote: "quote",
};

exports.Prisma.FacultyScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  designation: "designation",
  image: "image",
  about: "about",
  order: "order",
  published: "published",
  designation2: "designation2",
};

exports.Prisma.EventScalarFieldEnum = {
  id: "id",
  title: "title",
  description: "description",
  image: "image",
  date: "date",
  time: "time",
  reportLink: "reportLink",
  venue: "venue",
  guests: "guests",
  published: "published",
  type: "type",
  category: "category",
  maxTeamSize: "maxTeamSize",
  minTeamSize: "minTeamSize",
  brief: "brief",
  entryFee: "entryFee",
  qr: "qr",
  registrationsAvailable: "registrationsAvailable",
  endDate: "endDate",
  maxTeams: "maxTeams",
  notification: "notification",
};

exports.Prisma.LinksScalarFieldEnum = {
  id: "id",
  instagram: "instagram",
  linkedin: "linkedin",
  github: "github",
  userId: "userId",
  twitter: "twitter",
  order: "order",
  custom: "custom",
};

exports.Prisma.TeamScalarFieldEnum = {
  id: "id",
  attended: "attended",
  eventId: "eventId",
  name: "name",
  leaderId: "leaderId",
  transactionId: "transactionId",
  isConfirmed: "isConfirmed",
};

exports.Prisma.WinnersScalarFieldEnum = {
  id: "id",
  teamId: "teamId",
  eventId: "eventId",
  position: "position",
};

exports.Prisma.PlacementScalarFieldEnum = {
  id: "id",
  yearId: "yearId",
  studentId: "studentId",
};

exports.Prisma.CompanyScalarFieldEnum = {
  id: "id",
  companyName: "companyName",
  image: "image",
};

exports.Prisma.OfferScalarFieldEnum = {
  id: "id",
  companyId: "companyId",
  package: "package",
};

exports.Prisma.YearScalarFieldEnum = {
  id: "id",
  year: "year",
  companies: "companies",
};

exports.Prisma.PatentsScalarFieldEnum = {
  id: "id",
  patentId: "patentId",
  year: "year",
  title: "title",
  authors: "authors",
  inventorsName: "inventorsName",
  inventorsAddress: "inventorsAddress",
  certificate: "certificate",
};

exports.Prisma.PublicationScalarFieldEnum = {
  id: "id",
  authors: "authors",
  title: "title",
  publish_date: "publish_date",
  publisher: "publisher",
  journal: "journal",
  conference: "conference",
  link: "link",
  ranking: "ranking",
  impact_factor: "impact_factor",
  indexed: "indexed",
  publisher_conference: "publisher_conference",
  year: "year",
};

exports.Prisma.SortOrder = {
  asc: "asc",
  desc: "desc",
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
};

exports.Prisma.QueryMode = {
  default: "default",
  insensitive: "insensitive",
};

exports.Prisma.NullsOrder = {
  first: "first",
  last: "last",
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull,
};
exports.Role = exports.$Enums.Role = {
  USER: "USER",
  ADMIN: "ADMIN",
};

exports.EventType = exports.$Enums.EventType = {
  SOLO: "SOLO",
  TEAM: "TEAM",
};

exports.EventCategory = exports.$Enums.EventCategory = {
  PREVIOUS: "PREVIOUS",
  UPCOMING: "UPCOMING",
  CURRENT: "CURRENT",
};

exports.WinnerType = exports.$Enums.WinnerType = {
  FIRST: "FIRST",
  SECOND: "SECOND",
  THIRD: "THIRD",
  PARTICIPATION: "PARTICIPATION",
};

exports.Prisma.ModelName = {
  User: "User",
  Account: "Account",
  Session: "Session",
  Student: "Student",
  Core: "Core",
  Faculty: "Faculty",
  Event: "Event",
  Links: "Links",
  Team: "Team",
  Winners: "Winners",
  Placement: "Placement",
  Company: "Company",
  Offer: "Offer",
  Year: "Year",
  Patents: "Patents",
  Publication: "Publication",
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message;
        const runtime = getRuntime();
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message =
            "PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `" +
            runtime.prettyName +
            "`).";
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`;

        throw new Error(message);
      },
    });
  }
}

exports.PrismaClient = PrismaClient;

Object.assign(exports, Prisma);
